FROM hashicorp/terraform:1.3.5 as terraform

FROM regclient/regctl:edge-alpine as regctl

FROM golang:1.19.3-alpine as go

# install git, required by `go get`
RUN apk add --update git

RUN GO111MODULE=on go install github.com/raviqqe/liche@latest

FROM alpine:3.17 as gh

ENV GITHUB_CLI_VERSION=2.0.0
ADD https://github.com/cli/cli/releases/download/v${GITHUB_CLI_VERSION}/gh_${GITHUB_CLI_VERSION}_linux_amd64.tar.gz /tmp/gh.tgz

RUN tar \
  --strip-components=2 \
  --extract \
  --file /tmp/gh.tgz \
  gh_${GITHUB_CLI_VERSION}_linux_amd64/bin/gh && \
  mv -v gh /bin/gh

FROM alpine:3.17 as yq

ENV VERSION=v4.30.5
ENV BINARY=yq_linux_amd64

ADD https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY}.tar.gz /tmp/yq.tgz

RUN tar \
  --extract \
  --file /tmp/yq.tgz \
  ./${BINARY} && mv -v ${BINARY} /usr/local/bin/yq

FROM alpine:3.17

ENV AWSCLI_VERSION 1.18.4

RUN apk add --update \
  git make bash jq curl gpg gnupg less openssh patch && \
  apk --purge -v del py-pip && \
  rm -rf /var/cache/apk/* && \
  rm -rf $HOME/.cache

COPY --from=terraform /bin/terraform /usr/local/bin

COPY --from=regctl /usr/local/bin/regctl /usr/local/bin

COPY --from=gh  /bin/gh /usr/local/bin

COPY --from=yq  /usr/local/bin/yq /usr/local/bin

ENV GO_BIN /go/bin
ENV PATH "$GO_BIN:$PATH"

COPY --from=go /go/bin $GO_BIN

ENV BIN_3SCALE /opt/3scale/bin
ENV PATH "$BIN_3SCALE:$PATH"

ADD bin/ $BIN_3SCALE
RUN chmod -R 0755 $BIN_3SCALE
