version: 2.1
workflows:
  build:
    jobs:
    - build-all:
        filters:
          branches:
            ignore:
              - master
  latest:
    jobs:
    - build-n-push-latest:
        context: org-global
        filters:
          branches:
            only:
              - master
  release:
    jobs:
    - build-n-push-release:
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/

jobs:
  build-all:
    machine: true
    steps:
    - checkout
    - run: make build-all
  build-n-push-latest:
    machine: true
    steps:
    - checkout
    - run: make latest-build
    - run: docker login ${DOCKER_REGISTRY} -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
    - run: make latest-push
  build-n-push-release:
    machine: true
    steps:
    - checkout
    - run: make release-build
    - run: docker login ${DOCKER_REGISTRY} -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
    - run: make release-push