version: 2.1
workflows:
  build:
    jobs:
    - build-all:
        filters:
          branches:
            ignore:
              - main
  latest:
    jobs:
    - build-n-push-latest:
        context: org-global
        filters:
          branches:
            only:
              - main
  release:
    jobs:
    - build-n-push-release:
        context: org-global
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/

jobs:
  build-all:
    machine: true
    steps:
    - checkout
    - run: make build-all
  build-n-push-latest:
    machine: true
    steps:
    - checkout
    - run: make build-all-latest
    - run: docker login ${DOCKER_REGISTRY} -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
    - run: make push-all-latest
  build-n-push-release:
    machine: true
    steps:
    - checkout
    - run: TAG=${CIRCLE_TAG:-main} make build-all-release
    - run: docker login ${DOCKER_REGISTRY} -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
    - run: TAG=${CIRCLE_TAG:-main} make push-all-release