version: 2.1
workflows:
  build:
    jobs:
    - build-all:
        filters:
          branches:
            ignore:
              - master

jobs:
 build-all:
   machine: true
   steps:
     - checkout
     - run: make build-all
