name: release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Export release name
        run: |
          echo "NEW_RELEASE=$(make get-new-release)" >> $GITHUB_ENV

      - name: Build images
        run: TAG=${NEW_RELEASE:-latest} make build-all-release

      - name: Login to quay.io/3scale
        if: ${{ env.NEW_RELEASE != '' }}
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push new images
        if: ${{ env.NEW_RELEASE != '' }}
        run: TAG=${NEW_RELEASE:-latest} make push-all-release

      - name: Create a new draft-release in github
        if: ${{ env.NEW_RELEASE != '' }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.NEW_RELEASE }}"
          title: "${{ env.NEW_RELEASE }}"
          draft: true
