name: test

on:
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: quay.io/3scale/soyuz:test

      - name: Build CI Image
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile-ci
          platforms: linux/amd64,linux/arm64
          provenance: false
          push: false
          tags: quay.io/3scale/soyuz:test-ci
